package com.acme.entity;

import com.acme.validation.ValidationConstants;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.util.HashSet;
import java.util.Set;

/**
 * Using lecturerId as natural key for uniqueness.
 * ID is auto-generated by database, lecturerId serves as business identifier.
 */
@Entity
@Table(
    name = "lecturers",
    uniqueConstraints = @UniqueConstraint(
        columnNames = {"lecturer_id"},
        name = "uk_lecturer_id"
    )
)
@Getter
@Setter
@NoArgsConstructor
@ToString(exclude = "students") // Prevent circular reference in toString
public class Lecturer {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @NotBlank(message = "Name " + ValidationConstants.NOT_BLANK_MESSAGE)
    @Pattern(regexp = ValidationConstants.ALPHANUMERIC_PATTERN, message = "Name " + ValidationConstants.ALPHANUMERIC_MESSAGE)
    @Column(nullable = false)
    private String name;

    @NotBlank(message = "Surname " + ValidationConstants.NOT_BLANK_MESSAGE)
    @Pattern(regexp = ValidationConstants.ALPHANUMERIC_PATTERN, message = "Surname " + ValidationConstants.ALPHANUMERIC_MESSAGE)
    @Column(nullable = false)
    private String surname;

    @NotBlank(message = ValidationConstants.LECTURER_ID_MESSAGE)
    @Pattern(regexp = ValidationConstants.ALPHANUMERIC_PATTERN, message = "Lecturer ID " + ValidationConstants.ALPHANUMERIC_MESSAGE)
    @Column(name = "lecturer_id", nullable = false, unique = true)
    private String lecturerId;

    /**
     * Column names are explicit about referencing database IDs.
     */
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(
        name = "lecturer_student",
        joinColumns = @JoinColumn(name = "lecturer_db_id", referencedColumnName = "id"),
        inverseJoinColumns = @JoinColumn(name = "student_db_id", referencedColumnName = "id")
    )
    private Set<Student> students = new HashSet<>();

    public Lecturer(String name, String surname, String lecturerId) {
        this.name = name;
        this.surname = surname;
        this.lecturerId = lecturerId;
    }
    
    public void addStudent(Student student) {
        students.add(student);
        student.getLecturers().add(this);
    }

} 