spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/testdb
    driver-class-name: org.postgresql.Driver
    username: user
    password: password
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false